language: node_js
node_js:
  - '6'
before_install:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start
script: npm test
